"""active_members

Revision ID: a7021e70f30f
Revises: ba0b21439866
Create Date: 2019-10-04 13:23:59.288436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7021e70f30f'
down_revision = 'ba0b21439866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_member', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_users_active_member'), 'users', ['active_member'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_active_member'), table_name='users')
    op.drop_column('users', 'active_member')
    # ### end Alembic commands ###
