#!/bin/bash

echo "Creating database backup===="
./galacursussen/scripts/backup
echo "========================Done"

echo "Checking out new version===="
cd galacursussen
git pull
echo "========================Done"

echo "Building frontend==========="
npm install
npm run build
echo "========================Done"

echo "Restarting Services========="
sudo systemctl reload nginx
echo "========================Done"

cd
